language: node_js
node_js:
- lts/*
install:
  - npm ci
script:
- npm run build:dev
- npm run build
before_deploy:
- echo "Cleaning files..."
- rm -rf stylus
- rm .editorconfig
- rm package-*
branch:
  only:
  - master
deploy:
  skip_cleanup: true
  provider: npm
  email: $EMAIL
  api_key:
    secure: $API_KEY
  on:
    tags: true
